services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
    env_file:
      - .env
    depends_on:
      - db

  migrations:
    build: .
    command: ["uv", "run", "alembic", "upgrade", "head"]
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=online-shop
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: